app.name=kafka-cron-consumer
app.env=development
app.version=0.0.1
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
group.id=kafka-cron-group
